version: 2.1

jobs:
  build:
    working_directory: ~/circleci-caver-java
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: circleci-caver-java-{{ checksum "build.gradle" }}
      - run: ./gradlew build
  deploy:
    working_directory: ~/circleci-caver-java
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew release

workflows:
  version: 2.1
  caver-java-ci:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - hold